# Generated by Django 4.1.2 on 2022-11-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_payment_id_payment_order_id_payment_is_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paymemt_id',
            new_name='payment_id',
        ),
    ]
