# Generated by Django 4.1.2 on 2022-12-06 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_rename_food_and_logging_fees_student_food_and_lodging_fees_and_more'),
        ('payments', '0003_rename_paymemt_id_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sub_payment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ScoutPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_fees', models.IntegerField(default=0)),
                ('food_and_lodging_fees', models.IntegerField(default=0)),
                ('uniform_fees', models.IntegerField(default=0)),
                ('shoes_fees', models.IntegerField(default=0)),
                ('ccrup_fees', models.IntegerField(default=0)),
                ('cap_fees', models.IntegerField(default=0)),
                ('belt_fees', models.IntegerField(default=0)),
                ('admission_fees', models.IntegerField(default=0)),
                ('membership_fees', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
