# Generated by Django 4.1.3 on 2022-11-09 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='students.batch'),
            preserve_default=False,
        ),
    ]
