# Generated by Django 4.1.3 on 2022-11-09 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='admission_fees',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='book_fees',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='bp_fees',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='closing_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='course_fees',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='dress_fees',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='icard_fees',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='opening_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='picnic_fees',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='place',
            field=models.CharField(choices=[('COOCHBEHAR', 'Cooch Behar'), ('ALIPURDUAR', 'Alipurduar')], default='COOCHBEHAR', max_length=30),
        ),
        migrations.AddField(
            model_name='batch',
            name='puja_fees',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='registration_fees',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
