# Generated by Django 4.1.2 on 2022-11-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_admission_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online')], default='ONLINE', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'InActive')], default='ACTIVE', max_length=30),
        ),
    ]
