# Generated by Django 4.1.2 on 2022-11-12 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_payment_mode_alter_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=90, unique=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'ordering': ('-datetime',),
            },
        ),
    ]
