# Generated by Django 4.1.2 on 2022-11-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='registrationnumber',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
