# Generated by Django 4.1.2 on 2022-11-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_remove_student_qr_code_registrationnumber_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationnumber',
            name='qr_code',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
