# Generated by Django 4.1.2 on 2022-11-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_registrationnumber_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationnumber',
            name='qr_code',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
