# Generated by Django 4.1.2 on 2022-11-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_registrationnumber_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='adhaar_card',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='describe_queries',
            field=models.TextField(blank=True, null=True),
        ),
    ]
