# Generated by Django 4.1.2 on 2022-11-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_student_adhaar_card_student_describe_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='applying_for',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
