# Generated by Django 4.1.2 on 2022-11-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_student_applying_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='applying_for',
            field=models.TextField(blank=True, null=True),
        ),
    ]
