# Generated by Django 4.1.2 on 2022-11-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_student_applying_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('IN_REVIEW', 'In Review'), ('INACTIVE', 'InActive')], default='IN_REVIEW', max_length=30),
        ),
    ]
