# Generated by Django 4.1.2 on 2022-11-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_alter_student_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='adhaar_card',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
