# Generated by Django 4.1.2 on 2022-11-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_alter_student_adhaar_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='adhaar_card',
            field=models.FileField(blank=True, null=True, upload_to='adhaar_cards'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('IN_REVIEW', 'In Review'), ('INACTIVE', 'In Active')], default='IN_REVIEW', max_length=30),
        ),
    ]
