# Generated by Django 4.1.2 on 2022-11-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_alter_student_adhaar_card_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='applying_for',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
