# Generated by Django 4.1.2 on 2022-12-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_alter_student_applying_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pin_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='whatsapp_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
