# Generated by Django 4.1.2 on 2022-12-06 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_student_pin_code_student_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
