# Generated by Django 4.1.2 on 2022-12-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='belt_fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='cap_fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='ccrup_fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='food_and_logging_fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='membership_fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='shoes_fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='training_fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='uniform_fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_fees',
            field=models.IntegerField(default=0),
        ),
    ]
